#ifndef ND__RooTrackerVtxBase_h
#define ND__RooTrackerVtxBase_h
namespace ND {
class RooTrackerVtxBase;
} // end of namespace.
#include "TObject.h"
namespace ND {
class RooTrackerVtxBase : public TObject {
public:
// Nested classes declaration.
public:
// Data Members.
   RooTrackerVtxBase();
   RooTrackerVtxBase(const RooTrackerVtxBase & );
   virtual ~RooTrackerVtxBase();
   ClassDef(RooTrackerVtxBase,2); // Generated by MakeProject.
};
} // namespace
#endif